services:
  fastapi:
    build:
      context: ./api
    container_name: fastapi_server
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./api:/fastapi 
    networks:
      - app_network

  filter:
    build:
      context: ./filter
    container_name: filter_service
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./filter:/filter
      - ${HF_HUB}:/models
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - app_network

  ollama:
    image: ollama/ollama
    runtime: nvidia
    container_name: ollama
    env_file:
      - .env
    ports:
      - "11434:11434"
    volumes:
      - "${OLLAMA_MODELS_PATH}:/root/.ollama"
    networks:
      - app_network

networks:
  app_network:

volumes:
  rabbitmq: