services:
  fastapi:
    build: ./app
    container_name: fastapi_server
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - ollama
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OLLAMA_URL=http://ollama:11434
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
